<?php

namespace AppBundle\Repository;

/**
 * RoutesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoutesRepository extends \Doctrine\ORM\EntityRepository
{
}
