<?php

namespace AppBundle\Repository;

/**
 * routesSitesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class routesSitesRepository extends \Doctrine\ORM\EntityRepository
{
}
