<?php

namespace AppBundle\Repository;

/**
 * usersRoutesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class usersRoutesRepository extends \Doctrine\ORM\EntityRepository
{
}
